@Library('shared-library@aditya_SCRUM-510') _

properties([
    parameters([
        choice(
            name: 'action',
            choices: ['apply', 'destroy'],
            description: 'Choose the action to perform: apply or destroy'
        ),
        string(
            name: 'tfvarsFile',
            defaultValue: 'terraform.tfvars',
            description: 'Path to .tfvars file relative to terraformPath (optional)'
        )
    ])
])

networkskeletoncicdtemplate(
    repoUrl: 'https://github.com/Cloud-NInja-snaatak/wrapper-code.git',
    branchName: 'Aniruddh_SCRUM-527',
    credentialsId: 'github-token',
    terraformPath: 'env/dev/database/postgresql',
    message: "Approval for infrastructure ${params.action}",
    action: params.action,
    tfvarsFile: params.tfvarsFile ?: ''
)
